ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT =  /dev/ttyUSB0

USER_LIB_PATH = /home/pi/sketchbook/libraries
ARDUINO_LIBS = AccelStepper\
               arduino_ps2_mouse_master
BOARD_TAG =  atmega328

include /usr/share/arduino/Arduino.mk
